# Generated by Django 6.0.5 on 2026-06-15 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='bar',
            name='descripcion_corta',
            field=models.CharField(default='Pendiente de completar', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 15, 10, 41, 49, 248689, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='historia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='horario_apertura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bar',
            name='horario_cierre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bar',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='subzona',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bar',
            name='valoracion_media',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bar',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
