# Generated by Django 6.0.5 on 2026-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares', '0002_remove_bar_descripcion_bar_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='imagen',
            new_name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='horario_cierre',
        ),
        migrations.AddField(
            model_name='bar',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bar',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='horario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='localidad',
            field=models.CharField(default='Sevilla', max_length=100),
        ),
        migrations.AddField(
            model_name='bar',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='numero_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bar',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='subzona',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
