# Generated by Django 6.0.5 on 2026-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares', '0003_rename_imagen_bar_imagen_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='bar',
            name='ambiente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bar',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='especialidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='ideal_para',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bar',
            name='precio_medio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bar',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='localidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bar',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bar',
            name='valoracion_media',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
